### PR TITLE
Revert "Revert "Fully Implement Custom Reporters""

### PR DESCRIPTION
**Pull request by Mrcomputer1**
Reverts SharpScratchMod/Sharp#13

### CODE REVIEW

**Comment by Mrcomputer1** [comment]
I think I know what to do to fix there was no conflict.
DO NOT PUSH ANYTHING TO MASTER!

@DrKat123

**Comment by Mrcomputer1** [comment]
Fixed!

It now is `b[*]` instead `interp.*arg(b, *)` for accessing arg and `b:Array` instead of `b:Block` in the prim function

**Comment by Mrcomputer1** [comment]
Waiting for test....

**Comment by NoMod-Programming** [comment]
But if an argument NEEDS to be a number, as in the case of this block, just make sure that you use `interp.numarg(b[*])`

**Comment by Mrcomputer1** [comment]
Ok I didn't do that with the block I fixed (That DrKat added before merging)
Waiting for tests...

**Comment by NoMod-Programming** [comment]
Alright, and because custom booleans can report strings and numbers too, just make sure to use `interp.boolarg(b[*])` whenever needed to convert an argument to a boolean. Congratulations on custom reporters in Sharp!

**Comment by Mrcomputer1** [comment]
Ok

Thanks for doing custom reporters @NoMod-Programming. I will add you to the credit screen soon.

**Pull request merged**
