### PR TITLE
Fully Implement Custom Reporters

### PR DESCRIPTION
**Pull request by NoMod-Programming**
I did all the work for you; all you need to do is merge it 😺 :package:
This replaces #11

### CODE REVIEW

**Comment by Mrcomputer1** [comment]
WOW! Thanks!

@DrKat123 LOOK AT THIS!
@DrKat123 LOOK AT THIS!
@SharpScratchMod/project-owners LOOK AT THIS! (Kind of useless that team only contains me and DrKat123 :P

**Comment by ghost** [comment]
THANK YOU SO MUCH :smile:

**Comment by ghost** [comment]
wait, there's an error on the travis build

**Comment by ghost** [comment]
the errors need to be fixed

**Comment by ghost** [comment]
here is the error

**Comment by ghost** [comment]
FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':compileFlex'.
  
  > java.lang.Exception: mxmlc execution failed: /home/travis/build/SharpScratchMod/Sharp/src/util/GIFDecoder.as(37): col: 14 Warning: No constructor function was specified for class GIFDecoder.
  
  public class GIFDecoder {
               ^
  
  /home/travis/build/SharpScratchMod/Sharp/src/uiwidgets/ScrollFrameContents.as(34): col: 14 Warning: No constructor function was specified for class ScrollFrameContents.
  
  public class ScrollFrameContents extends Sprite {
               ^
  
  /home/travis/build/SharpScratchMod/Sharp/src/util/JSON.as(33): col: 14 Warning: No constructor function was specified for class JSON.
  
  public class JSON {
               ^
  
  /home/travis/build/SharpScratchMod/Sharp/src/svgutils/SVGDisplayRender.as(39): col: 14 Warning: No constructor function was specified for class SVGDisplayRender.
  
  public class SVGDisplayRender {
               ^
  
  /home/travis/build/SharpScratchMod/Sharp/src/com/adobe/utils/macro/AGALVar.as(10): col: 15 Warning: No constructor function was specified for class AGALVar.
  
    public class AGALVar
                 ^
  
  /home/travis/build/SharpScratchMod/Sharp/src/svgutils/SVGImportPath.as(33): col: 14 Warning: No constructor function was specified for class SVGImportPath.
  
  public class SVGImportPath {
               ^
  
  /home/travis/build/SharpScratchMod/Sharp/src/com/adobe/utils/macro/VM.as(5): col: 15 Warning: No constructor function was specified for class VM.
  
    public class VM
                 ^
  
  /home/travis/build/SharpScratchMod/Sharp/src/com/adobe/utils/AGALMacroAssembler.as(725): col: 16 Warning: No constructor function was specified for class Macro.
  
  internal class Macro 
                 ^
  
  /home/travis/build/SharpScratchMod/Sharp/src/com/adobe/utils/macro/ExpressionParser.as(159): col: 7 Warning: No constructor function was specified for class OpInfo.
  
  class OpInfo
        ^
  
  /home/travis/build/SharpScratchMod/Sharp/src/com/adobe/utils/macro/BinaryExpression.as(3): col: 17 Warning: No constructor function was specified for class BinaryExpression.
  
    internal class BinaryExpression extends com.adobe.utils.macro.Expression
                   ^
  
  /home/travis/build/SharpScratchMod/Sharp/src/uiwidgets/VariableTextField.as(26): col: 14 Warning: No constructor function was specified for class VariableTextField.
  
  public class VariableTextField extends TextField {
               ^
  
  /home/travis/build/SharpScratchMod/Sharp/src/ui/parts/UIPart.as(41): col: 14 Warning: No constructor function was specified for class UIPart.
  
  public class UIPart extends Sprite {
               ^
  
  /home/travis/build/SharpScratchMod/Sharp/src/interpreter/Thread.as(153): col: 7 Warning: No constructor function was specified for class StackFrame.
  
  class StackFrame {
        ^
  
  /home/travis/build/SharpScratchMod/Sharp/src/svgeditor/DrawProperties.as(21): col: 14 Warning: No constructor function was specified for class DrawProperties.
  
  public class DrawProperties {
               ^
  
  /home/travis/build/SharpScratchMod/Sharp/src/extensions/ExtensionManager.as(476): col: 9 Warning: Duplicate variable definition.
  
  ```
            var activeThread:Thread = app.interp.activeThread;
                ^
  ```
  
  /home/travis/build/SharpScratchMod/Sharp/src/scratch/ScratchObj.as(47): col: 14 Warning: No constructor function was specified for class ScratchObj.
  
  public class ScratchObj extends Sprite {
               ^
  
  /home/travis/build/SharpScratchMod/Sharp/src/util/ZipIO.as(24): col: 14 Warning: No constructor function was specified for class ZipIO.
  
  public class ZipIO {
               ^
  
  /home/travis/build/SharpScratchMod/Sharp/src/util/ZipIO.as(316): col: 7 Warning: No constructor function was specified for class Entry.
  
  class Entry {
        ^
  
  /home/travis/build/SharpScratchMod/Sharp/src/primitives/Primitives.as(240): col: 25 Error: Call to a possibly undefined method arg through a reference with static type interpreter:Interpreter.
  
  ```
    var a:String = interp.arg(b, 0);
                          ^
  ```
  
  /home/travis/build/SharpScratchMod/Sharp/src/primitives/Primitives.as(243): col: 32 Error: Incorrect number of arguments.  Expected no more than 1.
  
  ```
    var j:int = interp.numarg(b, 2);
                                 ^
  ```
  
  /home/travis/build/SharpScratchMod/Sharp/src/primitives/Primitives.as(244): col: 28 Error: Incorrect number of arguments.  Expected no more than 1.
  
  ```
    for(i = interp.numarg(b, 1); i < j + 1; i++) {
                             ^
  ```
  
  /home/travis/build/SharpScratchMod/Sharp/src/primitives/SensingPrims.as(39): col: 49 Warning: variable 'dialogBoxActive' has no type declaration.
  
    private var dialogBoxAllowed = 10; private var dialogBoxActive = 0; // TODO: Add hidden setting for dialog boxs allowed
                                                   ^
  
  /home/travis/build/SharpScratchMod/Sharp/src/primitives/SensingPrims.as(39): col: 14 Warning: variable 'dialogBoxAllowed' has no type declaration.
  
    private var dialogBoxAllowed = 10; private var dialogBoxActive = 0; // TODO: Add hidden setting for dialog boxs allowed
                ^
  
  /home/travis/build/SharpScratchMod/Sharp/src/Scratch.as(1131): col: 31 Warning: return value for function 'helpMenuItemCredits' has no type declaration.
  
  ```
    function helpMenuItemCredits(){
                                ^
  ```
  
  /home/travis/build/SharpScratchMod/Sharp/src/Scratch.as(1134): col: 33 Warning: return value for function 'helpMenuItemReportBug' has no type declaration.
  
  ```
    function helpMenuItemReportBug(){
                                  ^
  ```
  
  /home/travis/build/SharpScratchMod/Sharp/src/Scratch.as(1137): col: 29 Warning: return value for function 'helpMenuItemAbout' has no type declaration.
  
  ```
    function helpMenuItemAbout(){
                              ^
  ```
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
  BUILD FAILED
  Total time: 26.321 secs
  The command "./gradlew build -Ptarget=11.6" failed and exited with 1 during .
  Your build has been stopped.

**Pull request merged**
